name: ML Pipeline CI

on:
  push:
    paths:
      - '**/*.py'
      - 'Makefile'
      - 'data/**'
      - 'tests/**'
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # indispensable pour pousser sur GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint & Test
        run: |
          . venv/bin/activate
          make lint
          make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true                                 # ← push activé
          tags: |
            ghcr.io/${{ github.repository_owner }}/titanic:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/titanic:latest

      - name: Trigger Jenkins
        run: |
          curl -X POST ${{ secrets.JENKINS_WEBHOOK }} \
            --data-urlencode "IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/titanic:${{ github.sha }}"