name: ML Pipeline CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint & Test
        run: |
          . venv/bin/activate
          make lint
          make test

      - name: Run pipeline if lint OK
        run: |
          . venv/bin/activate
          make all
